version: '3'

services:
  main:
    build: .
    image: matsearch-vectorize
    command: |
      bash -c '
        source activate deepchem
        python app.py
      '
    volumes:
      - ./:/app
      - ../data:/data
